### ISSUE TITLE
Where are the pictures ?

### ISSUE THREAD

**Issue by coliss86** [AndunHH/spacemouse#25]
Hi, 

in https://github.com/AndunHH/spacemouse/commit/b4742517629bafdfebaed9a3dce551f5aa3ecd38, the link to the picture has been updated but this file is not in the repository. Usually, there is a folder `pictures/` containing those files.
Thus, in the readme.md, the link to those picture is written with `![analog](pictures/file1.jpg)`.

What do you think ?

**Comment by AndunHH** [comment]
I uploaded the pictures to GitHub just by dragging them into the editor. They are therefore uploaded into a hidden assets folder and named with a hash.

Here on GitHub, I can see the pictures. Can't you? 

Or are you talking about the downloaded repo, when viewing and editing the readme offline?

We can go with a distinct pictures folder, the way of uploading via the editor was just more convenient.

**Comment by coliss86** [comment]
Sure, I can view those pictures but they are not part of the repository. It makes more difficult to see the differences in a PR for example.

**Comment by coliss86** [comment]
Perfect ! Thanks :)
