### ISSUE TITLE
Getting more keys working

### ISSUE THREAD

**Issue by AndunHH** [AndunHH/spacemouse#28]
This issue shall enable us, to get the keys working properly. Therefore this is starting with some investigation and collecting links:

- https://github.com/FreeSpacenav/spacenavd/discussions/106
 - the remapping of scrambled space mouse pro buttons:  https://github.com/FreeSpacenav/spacenavd/blob/master/src%2Fdev.c#L442

**Comment by AndunHH** [comment]
There are now more keys working and other key numbers and bits can be added easily. Therefore I close this issue.

**Comment by coliss86** [comment]
Nice work, can't wait to test it !
