### ISSUE TITLE
PINLIST is wrong

### ISSUE THREAD

**Issue by coliss86** [AndunHH/spacemouse#5]
Hi,

There is a mistake in the code about pin assignment to joysticks. 
The order in the code is:
```
int PINLIST[8] = { // The positions of the reads
  A0, // X-axis A
  A1, // Y-axis A
  A2, // X-axis B
  A3, // Y-axis B
  A6, // X-axis C
  A7, // Y-axis C
  A8, // X-axis D
  A9  // Y-axis D
};
```

but according to the wiring diagram from TeachingTech, it is:
```
int PINLIST[8] = {
    // The positions of the reads
    A1, // X-axis A
    A0, // Y-axis A
    A3, // X-axis B
    A2, // Y-axis B
    A7, // X-axis C
    A6, // Y-axis C
    A9, // X-axis D
    A8  // Y-axis D
};
```

it also explains with my mouse is not working :)

**Comment by AndunHH** [comment]
I just commited a change to put the pin definitions into a config.h file so everyone can have there on pin settings. And we don't overwrite the pin mapping or calibration, when changing other stuff in the code. You just need to copy and rename the config_sample.h to config.h.

Please check, if this resolves this issue.

**Comment by coliss86** [comment]
Fixed with the new `config.h`
