### ISSUE TITLE
DY going from -350 to 0 to -24150 as I rotate knob

### ISSUE THREAD

**Issue by Bradleydof** [AndunHH/spacemouse#53]
I am completely new to the online forum thing (horrible antisocial creature I am) so please excuse anything I may have missed or done wrong.
I cannot seem to figure out how to get the DY axis to report correctly. All other axis are -350 to 0 to 350.

It does go to 0, but either way I push the stick it goes negative. One end is -350 and the other end is -24150. I am really hoping it is just something stupid I have done and the fix will be an easy one.

I forgot to add that the raw values do go from 0 to 1023 as expected.

**Comment by Bradleydof** [comment]
Ugh,
I am embarrassed. My friend noticed a missing comma. problem solved. sorry.

**Comment by Bradleydof** [comment]
closed

**Comment by AndunHH** [comment]
I'm happy you figured it out! ;)
