### ISSUE TITLE
Old branches should be deleted

### ISSUE THREAD

**Issue by coliss86** [AndunHH/spacemouse#55]
Hi, 

very nice work :)

Branches associated to merged PR should be deleted in order to have a clean repo :)

Cheers

**Comment by coliss86** [comment]
Moreover, you can setup your repo to delete branch when the PR is merged

**Comment by AndunHH** [comment]
Yes! Good suggestions, I deleted the old ones at ticked the corresponding setting!

Thanks for the hint!
